### ISSUE TITLE
2 feature requests

### ISSUE THREAD

**Issue by msalini** [scubajeff/Setter#16]
- Add "translate with setter" in context menu
- Prevent recurrent cookie popup in deepl webview and set it up automatically to accept only essential cookies

With these two, the app would reach feature parity with deepl (f-droid) app.

**Comment by scubajeff** [comment]
if you mean text selection context menu, there is a translate item along side with search in setter too. 

DeepL changed their source recently, that annoying cookie notice popup comes back again. Will look into this.

**Comment by msalini** [comment]
Hi Jeff,

yes I meant the text selection context menu.
I have also the deepl f-droid app (https://f-droid.org/en/packages/com.example.deeplviewer) installed and the "translate" slot seems to have been taken over by that app, so I do not see (or enable) any translation with setter within that menu. Something you may wish to test.
I am on LineageOS 17.1 (Android 10).

Also regarding that annoying popup, the afore-mentioned deepl app doesn't show the cookie popup at all. You can reuse their trick ;-)

Also, on a different note, is there any plans to make more search engines (aside from the main and the local one) configurable? I personally do not need so much content in chinese or twitter or reddit, while you would rather have other engines installed.

One option would be:

- Ability to create custom tabs
- Ability to import opensearch plugins (https://mycroftproject.com/search-engines.html) to populate the tabs.

**Comment by scubajeff** [comment]
@msalini 

Release 0.1.14 is live on Google Play now, and soon on F-Droid too. This release will close the cookie consent popup automatically. However, this is an on-going game, whenever they change the source script, fix have to be worked on again.

I will test the context menu issue.

Regarding the engines customization, it can be done, but it's not a quick fix, and honestly my focus right now is my other project 'Les Pas'.

**Comment by msalini** [comment]
Thanks for the quick fix @scubajeff  !

As for the configurable search engines and tabs, I totally get it that it requires a complete rewrite of the app. I was only wondering whether you see the app developing towards, in the future. That's it :-)

I do appreciate all the hard work you have put into this quite unique app (at least in the f-droid repository)

:-)

**Comment by scubajeff** [comment]
@msalini I finally got the idea of a "Translate" button. It's a feature introduced in Android Q. New release of Setter is pushing out to both app markets. Thank you very much for your inspiration. This really save me and others a lot of hustle finding and clicking the 'Look up' menu.
