### ISSUE TITLE
Stuck in settings screen

### ISSUE THREAD

**Issue by theAkito** [scubajeff/Setter#2]
When you open the app, you are in a settings screen, where you choose the search engines and optionally install ColorDict.

There is no button to get out of that view.

If you enabled some gestures for changing the view, then that was a bad idea, because Android 11 has immersive gesture mode, so you cannot implement swipe gestures for your app, because they are overridden by the Android 11 swipe gestures.

Otherwise, if there are no gestures in your app, then there is a missing button to change views.

Using newest F-Droid version on Android 11 AOSP based custom ROM.

**Comment by scubajeff** [comment]
What do you mean by "change views"? If you are talking about leaving the setting screen, just use navigation bar or system gesture to go back to go to Home screen. If you are concerning about the setting not being saved, don't worry, it will be saved right after you changed it.

**Comment by ssokhey** [comment]
I am using GrapheneOS. When I open the app is all I see a screen where I can just change stuff as the person above said. Can't search.

Downloaded via F-Droid.

![Screenshot_20201223-134408](https://user-images.githubusercontent.com/16058459/102974692-f8c91900-4524-11eb-9006-bed49dc425ce.png)

**Comment by theAkito** [comment]
> The navigation via gesture just exits the app.
> Can't search.

Precisely.

**Comment by scubajeff** [comment]
to search: press and hold the home button or highlight text in other app and choose search in context menu, or share a piece of text to setter. to reverse search image, share image file to setter. 

the idea is to integrate setter into your existing work flow rather than a whole new search interface.

**Comment by theAkito** [comment]
I get weird behaviour, when I am going to home through the swipe gesture. It disappears from my recent apps list, after going home and closes weirdly. Perhaps it crashes?

Or, it's simply the case that we do not have a home button to hold, that's all.

If the home button thing is so important, then there needs to be a button inside the app, for those who do not have the antiquated home button in use. This way you can make it work on antiquated and new phones.

**Comment by scubajeff** [comment]
it's a feature, a setting screen should not stay in recent app list.

**Comment by theAkito** [comment]
Okay, good to know.
So there needs to be a dedicated "go back" or "Start" button or something similar.

**Comment by scubajeff** [comment]
no button. it's designed to replace assistant. see this page for how to activate it in full gesture mode. https://www.techrepublic.com/article/how-to-access-google-assistant-with-fully-gestural-navigation/

**Comment by theAkito** [comment]
I get that. Still, not even this weird diagonal gesture works. It just removes the launcher view and shows nothing but the background. Why not add a compatability setting, that allows hiding the button? I mean it's better to have something work, than to strictly never break design rules. ;)

**Comment by scubajeff** [comment]
almost forgot, u can also add a widget on the desktop.

**Comment by AlanSanchezP** [comment]
@theAkito you enabled setter as your assistant app? I just faced this same issue and it got solved by selecting setter as assistant app. Before that, all I got was a black gradient on the top of my screen for a secons, but now it works.

It would be great to have this documented in the readme file tho.

**Comment by kseistrup** [comment]
I, too, came here to report that I can't get out of the Settings screen. When so many people feel they're stuck, it indicates an anti-feature or missing relevant documentation.

**Comment by rikishi0071** [comment]
As I understand, Setter works like Google search widget so it looks like this app is a FOSS alternative to classic Google Search app

**Comment by scubajeff** [comment]
agree. i also review the readme. i might actually have said the same thing there "It can serve as a system-wide assistant app or can be launched by using widget or in selected text context menu." however, i could have made it more clearly. 
is not my intention to make a shinny new search interface, just want to streamline the daily workflow, make it more like working on the computer where you will have many handy tools for search and translation.


> As I understand, Setter works like Google search widget so it looks like this app is a FOSS alternative to classic Google Search app

**Comment by tomas4** [comment]
You can see users are confused. I was also, then figuted it out. But I think updating Readme is not enough, apps main functions should work intuitively without reading docs. It would be ideal after closing settings to show an simple text information, something like "Now you are all set. Use the aop by sharing text or images to Setter from other apps, or add widget. More in Readme (link)." And a button "Do not show again" would be nice.

**Comment by Casper-09** [comment]
what about using [App shortcuts](https://developer.android.com/guide/topics/ui/shortcuts) for Settings??
something like this :
<img src="https://raw.githubusercontent.com/MyOS-Android/my.android.search/main/Screenshots/5.png" width="40%">

**Comment by scubajeff** [comment]
Busying working on my other app Les Pas, will get back to this later.

**Comment by scubajeff** [comment]
Latest release can launch search directly in Setting screen. Closed
