### ISSUE TITLE
Unclear Usage Information about Reverse Image Search

### ISSUE THREAD

**Issue by smith901** [scubajeff/Setter#22]
After reading closed Issue #2, I was more confused. Ended up trying stuff until it worked from the share menu.

A sentence or two when first ran would be a big help. I usually hate those "_swipe until done because this information is sooooo important_" tutorials when apps first start but this app needs one or something. No one expects a settings page to be the 1st and ONLY thing an app shows.
All those pics in F-Droid made this ultra confusing. I expected the app to have one of those pages shown in the pics. Didn't get to them until I got the app "working".

Yes, app works out of the box. **App is rather unintuitive and confusing to get it to work.**

**Comment by odnar-dev** [comment]
this is the same reason why i made my own [fork](https://github.com/MyOS-Android/my.android.search), you can try it from [here](https://github.com/MyOS-Android/my.android.search/releases)
if @scubajeff want , i can make a pr with the changes

**Comment by scubajeff** [comment]
@odnar-dev Your work looks amazing. Unfortunately, I don't think I have enough time to work on this project, most of my attention is now on my other projects like Les Pas. Setter's code base is really a mess right now, if I can spare some time later, re-factoring is option number 1.

**Comment by smith901** [comment]
Understood. Keep on working on what you love devs. Best I can do is use and give feedback. I write Chicken Code to go with my chicken scratch handwriting so all of this is amazing to me. 🤣😘🤓
