### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by rikishi0071** [scubajeff/Setter#4]
I liked this app! It looks like now we have a FOSS replacement for proprietary Google Search widget :)

I'd like to translate this app and widget to Russian. Are any strings avaliable for translation?

**Comment by scubajeff** [comment]
i have seen some github project integrated with Weblate for translation stuff. but i have no idea how to streamline it. you can always clone this project and start translation in Android Studio, there is a very basic but solid translation editor there, and submit pull request back in github.

**Comment by scubajeff** [comment]
my bad. there is much more easy way, leave your email address here, we can exchange the string file.

**Comment by rikishi0071** [comment]
I wrote an e-mail to you

**Comment by gugus2000** [comment]
I can translate it to french too

**Comment by scubajeff** [comment]
@gugus2000 please leave your email here so that I can send you the string file. Thought I myself am learning French right now, it's better to let it done by professional. Merci!

**Comment by gugus2000** [comment]
gugus2000@protonmail.com (I'm not a professional but a native, so this will not be the best translation ^^)

**Comment by scubajeff** [comment]
@rikishi0071 @gugus2000 thank you two for translating this app. your works will be merged in the next release.
