### ISSUE TITLE
Auto Delete Cookies & Force Dark Mode

### ISSUE THREAD

**Issue by yant0** [scubajeff/Setter#6]
### Auto Delete Cookies & Force Dark Mode ###

Im not sure if the app auto delete cookies that would be a great feature, but im mostly want the second feature ( darkmode ) since im a night owl and got sleep deprivation. thanks

/im sorry i misclicked enter when first typing the issue im not sure of what to do since im new to github :p
//and thanks for making this wonderful app !!

**Comment by scubajeff** [comment]
setter is merely a wrap up of android system webview accessing different search engine. most of it's UI are used for displaying web content, so a dark mode won't help much.

**Comment by scubajeff** [comment]
release 0.1.8 added dark theme and auto delete cookie support
