### ISSUE TITLE
F droid Broken

### ISSUE THREAD

**Issue by yant0** [scubajeff/Setter#7]
Couldnt search anything
updated from f droid
re-installed from f droid
same result

**Comment by marcdw1289** [comment]
Works fine for me. Installed from F-Droid.

What are the steps you are taking?
I selected some text, selection menu (copy, paste, etc.) comes up. Tap on its three-dot menu and choose either "Look up" or "Search in Setter".
Worked out fine.

Maybe clear cache/data and try again or uninstall/reinstall.

**Comment by yant0** [comment]
any search, select, widget, assistant dont work for me. i cleared cache, data, and re installed still wouldnt work. works flawlessly on previous version

**Comment by yant0** [comment]
Changed my rom works now
