### ISSUE TITLE
Ads 🗿

### ISSUE THREAD

**Issue by NSTAdventure** [scubajeff/Setter#9]
Developer you said on description this app will maintain our privacy right?

Then why ads still allowed?

🗿🗿🗿🗿🗿🗿

**Comment by scubajeff** [comment]
what ads? if you mean ads from Colordict, you can uninstall it and use web translator instead.

**Comment by NSTAdventure** [comment]
> what ads? if you mean ads from Colordict, you can uninstall it and use web translator only.

It's on setter if not why i open issues here? 

Okay i will send ss soon please don't close this issues
